services:
  - type: web
    name: mybarber
    runtime: docker
    plan: free
    region: virginia
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/servicos
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: mybarber-db
          property: host
      - key: DB_PORTA
        fromDatabase:
          name: mybarber-db
          property: port
      - key: DB_NOME
        fromDatabase:
          name: mybarber-db
          property: database
      - key: DB_USUARIO
        fromDatabase:
          name: mybarber-db
          property: user
      - key: DB_SENHA
        fromDatabase:
          name: mybarber-db
          property: password
      - key: JWT_SEGREDO
        generateValue: true
      - key: ADMIN_NOME
        value: Administrador
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_TELEFONE
        sync: false
      - key: ADMIN_SENHA
        sync: false
      - key: DOCUMENTACAO_API_HABILITADA
        value: "false"
      - key: LEMBRETE_HABILITADO
        value: "false"
      - key: EMAIL_HABILITADO
        value: "false"

databases:
  - name: mybarber-db
    plan: free
    region: virginia
    databaseName: mybarber
    user: mybarber
