--liquibase formatted sql

--changeset arturlealm:001-criar-tabela-clientes
CREATE TABLE clientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    telefone VARCHAR(20) NOT NULL,
    email VARCHAR(254) NOT NULL,
    cpf VARCHAR(14) NOT NULL,
    CONSTRAINT uk_clientes_email UNIQUE (email),
    CONSTRAINT uk_clientes_cpf UNIQUE (cpf)
);
--rollback DROP TABLE clientes;
