--liquibase formatted sql

--changeset arturlealm:004-criar-tabela-funcionarios
CREATE TABLE funcionarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    email VARCHAR(254) NOT NULL,
    cpf VARCHAR(11),
    telefone VARCHAR(11) NOT NULL,
    senha_hash VARCHAR(100) NOT NULL,
    tipo VARCHAR(20) NOT NULL,
    realiza_atendimentos BOOLEAN NOT NULL DEFAULT TRUE,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_funcionarios_email UNIQUE (email),
    CONSTRAINT uk_funcionarios_cpf UNIQUE (cpf),
    CONSTRAINT ck_funcionarios_tipo CHECK (tipo IN ('BARBEIRO', 'ADMINISTRADOR'))
);
--rollback DROP TABLE funcionarios;
