--liquibase formatted sql

--changeset arturlealm:005-criar-tabela-filiais
CREATE TABLE filiais (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    telefone VARCHAR(11),
    endereco VARCHAR(255),
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_filiais_nome UNIQUE (nome)
);

INSERT INTO filiais (nome) VALUES ('Matriz');

ALTER TABLE funcionarios ADD COLUMN filial_id BIGINT;
UPDATE funcionarios SET filial_id = (SELECT id FROM filiais WHERE nome = 'Matriz');
ALTER TABLE funcionarios ALTER COLUMN filial_id SET NOT NULL;
ALTER TABLE funcionarios ADD CONSTRAINT fk_funcionarios_filial FOREIGN KEY (filial_id) REFERENCES filiais (id);
CREATE INDEX ix_funcionarios_filial ON funcionarios (filial_id);
