--liquibase formatted sql

--changeset arturlealm:006-criar-tabelas-servicos
CREATE TABLE servicos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    descricao VARCHAR(255),
    duracao_minutos INTEGER NOT NULL,
    preco NUMERIC(10, 2) NOT NULL,
    ordem_exibicao INTEGER NOT NULL DEFAULT 0,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_servicos_nome UNIQUE (nome),
    CONSTRAINT ck_servicos_duracao CHECK (duracao_minutos >= 0),
    CONSTRAINT ck_servicos_preco CHECK (preco >= 0)
);

CREATE TABLE combinacoes_servicos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    descricao VARCHAR(255),
    ordem_exibicao INTEGER NOT NULL DEFAULT 0,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_combinacoes_servicos_nome UNIQUE (nome)
);

CREATE TABLE combinacoes_servicos_itens (
    combinacao_servico_id BIGINT NOT NULL REFERENCES combinacoes_servicos (id),
    servico_id BIGINT NOT NULL REFERENCES servicos (id),
    PRIMARY KEY (combinacao_servico_id, servico_id)
);

INSERT INTO servicos (nome, descricao, duracao_minutos, preco, ordem_exibicao) VALUES
    ('Cabelo', 'Corte de cabelo', 30, 40.00, 1),
    ('Barba', 'Barba completa', 30, 30.00, 2),
    ('Sobrancelha', 'Incluída no atendimento de cabelo e barba', 0, 0.00, 3);

INSERT INTO combinacoes_servicos (nome, descricao, ordem_exibicao) VALUES
    ('Cabelo', 'Corte de cabelo', 1),
    ('Barba', 'Barba completa', 2),
    ('Cabelo e barba', 'Corte de cabelo e barba, com sobrancelha inclusa', 3);

INSERT INTO combinacoes_servicos_itens (combinacao_servico_id, servico_id)
SELECT c.id, s.id FROM combinacoes_servicos c JOIN servicos s ON s.nome = 'Cabelo' WHERE c.nome = 'Cabelo';
INSERT INTO combinacoes_servicos_itens (combinacao_servico_id, servico_id)
SELECT c.id, s.id FROM combinacoes_servicos c JOIN servicos s ON s.nome = 'Barba' WHERE c.nome = 'Barba';
INSERT INTO combinacoes_servicos_itens (combinacao_servico_id, servico_id)
SELECT c.id, s.id FROM combinacoes_servicos c JOIN servicos s ON s.nome IN ('Cabelo', 'Barba', 'Sobrancelha') WHERE c.nome = 'Cabelo e barba';
