--liquibase formatted sql

--changeset arturlealm:007-criar-tabelas-agenda
CREATE TABLE jornadas_funcionarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    funcionario_id BIGINT NOT NULL REFERENCES funcionarios (id),
    dia_semana VARCHAR(10) NOT NULL,
    hora_inicio TIME NOT NULL,
    hora_fim TIME NOT NULL,
    CONSTRAINT ck_jornadas_funcionarios_dia_semana
        CHECK (dia_semana IN ('SEGUNDA', 'TERCA', 'QUARTA', 'QUINTA', 'SEXTA', 'SABADO', 'DOMINGO')),
    CONSTRAINT ck_jornadas_funcionarios_horario CHECK (hora_fim > hora_inicio)
);
CREATE INDEX ix_jornadas_funcionarios_funcionario ON jornadas_funcionarios (funcionario_id);

CREATE TABLE ajustes_agenda (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filial_id BIGINT NOT NULL REFERENCES filiais (id),
    funcionario_id BIGINT REFERENCES funcionarios (id),
    data DATE NOT NULL,
    tipo VARCHAR(10) NOT NULL,
    hora_inicio TIME,
    hora_fim TIME,
    motivo VARCHAR(255),
    criado_por_funcionario_id BIGINT NOT NULL REFERENCES funcionarios (id),
    criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_ajustes_agenda_tipo CHECK (
        (tipo = 'FECHADO' AND hora_inicio IS NULL AND hora_fim IS NULL)
        OR (tipo = 'ABERTO' AND hora_inicio IS NOT NULL AND hora_fim IS NOT NULL AND hora_fim > hora_inicio)
    )
);
CREATE UNIQUE INDEX uk_ajustes_agenda_funcionario_data ON ajustes_agenda (funcionario_id, data)
    WHERE funcionario_id IS NOT NULL;
CREATE UNIQUE INDEX uk_ajustes_agenda_filial_data ON ajustes_agenda (filial_id, data)
    WHERE funcionario_id IS NULL;
CREATE INDEX ix_ajustes_agenda_data ON ajustes_agenda (data);
