--liquibase formatted sql

--changeset arturlealm:008-criar-tabelas-agendamentos
CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE TABLE agendamentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT NOT NULL REFERENCES clientes (id),
    funcionario_id BIGINT NOT NULL REFERENCES funcionarios (id),
    filial_id BIGINT NOT NULL REFERENCES filiais (id),
    inicio TIMESTAMP NOT NULL,
    fim TIMESTAMP NOT NULL,
    status VARCHAR(20) NOT NULL,
    valor_tabela NUMERIC(10, 2) NOT NULL,
    valor_cobrado NUMERIC(10, 2),
    observacao VARCHAR(255),
    concluido_em TIMESTAMPTZ,
    concluido_por_funcionario_id BIGINT REFERENCES funcionarios (id),
    cancelado_em TIMESTAMPTZ,
    cancelado_por VARCHAR(20),
    motivo_cancelamento VARCHAR(255),
    criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_agendamentos_periodo CHECK (fim > inicio),
    CONSTRAINT ck_agendamentos_status CHECK (status IN ('AGENDADO', 'CONCLUIDO', 'CANCELADO', 'NAO_COMPARECEU')),
    CONSTRAINT ck_agendamentos_cancelado_por CHECK (cancelado_por IS NULL OR cancelado_por IN ('CLIENTE', 'FUNCIONARIO')),
    CONSTRAINT ck_agendamentos_valor_cobrado CHECK (valor_cobrado IS NULL OR valor_cobrado >= 0),
    CONSTRAINT ex_agendamentos_horario_funcionario EXCLUDE USING gist (
        funcionario_id WITH =,
        tsrange(inicio, fim) WITH &&
    ) WHERE (status IN ('AGENDADO', 'CONCLUIDO'))
);
CREATE INDEX ix_agendamentos_funcionario_inicio ON agendamentos (funcionario_id, inicio);
CREATE INDEX ix_agendamentos_cliente_inicio ON agendamentos (cliente_id, inicio);
CREATE INDEX ix_agendamentos_filial_inicio ON agendamentos (filial_id, inicio);

CREATE TABLE agendamentos_itens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agendamento_id BIGINT NOT NULL REFERENCES agendamentos (id),
    servico_id BIGINT NOT NULL REFERENCES servicos (id),
    nome_servico VARCHAR(100) NOT NULL,
    duracao_minutos INTEGER NOT NULL,
    preco_tabela NUMERIC(10, 2) NOT NULL
);
CREATE INDEX ix_agendamentos_itens_agendamento ON agendamentos_itens (agendamento_id);
CREATE INDEX ix_agendamentos_itens_servico ON agendamentos_itens (servico_id);
