--liquibase formatted sql

--changeset arturlealm:009-criar-tabela-jornadas-filiais
CREATE TABLE jornadas_filiais (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filial_id BIGINT NOT NULL REFERENCES filiais (id),
    dia_semana VARCHAR(10) NOT NULL,
    hora_inicio TIME NOT NULL,
    hora_fim TIME NOT NULL,
    CONSTRAINT ck_jornadas_filiais_dia_semana
        CHECK (dia_semana IN ('SEGUNDA', 'TERCA', 'QUARTA', 'QUINTA', 'SEXTA', 'SABADO', 'DOMINGO')),
    CONSTRAINT ck_jornadas_filiais_horario CHECK (hora_fim > hora_inicio)
);
CREATE INDEX ix_jornadas_filiais_filial ON jornadas_filiais (filial_id);

INSERT INTO jornadas_filiais (filial_id, dia_semana, hora_inicio, hora_fim)
SELECT f.id, j.dia_semana, j.hora_inicio, j.hora_fim
FROM filiais f
CROSS JOIN (VALUES
    ('SEGUNDA', TIME '08:00', TIME '18:00'),
    ('TERCA', TIME '08:00', TIME '18:00'),
    ('QUARTA', TIME '08:00', TIME '18:00'),
    ('QUINTA', TIME '08:00', TIME '18:00'),
    ('SEXTA', TIME '08:00', TIME '18:00'),
    ('SABADO', TIME '08:00', TIME '15:00'),
    ('DOMINGO', TIME '09:00', TIME '12:00')
) AS j (dia_semana, hora_inicio, hora_fim)
WHERE f.nome = 'Matriz';
