--liquibase formatted sql

--changeset arturlealm:010-criar-tabela-tokens-redefinicao-senha
CREATE TABLE tokens_redefinicao_senha (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash VARCHAR(64) NOT NULL,
    tipo_conta VARCHAR(20) NOT NULL,
    usuario_id BIGINT NOT NULL,
    expira_em TIMESTAMPTZ NOT NULL,
    usado_em TIMESTAMPTZ,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_tokens_redefinicao_senha_hash UNIQUE (token_hash),
    CONSTRAINT ck_tokens_redefinicao_senha_tipo CHECK (tipo_conta IN ('CLIENTE', 'FUNCIONARIO'))
);
CREATE INDEX ix_tokens_redefinicao_senha_usuario ON tokens_redefinicao_senha (tipo_conta, usuario_id);
--rollback DROP TABLE tokens_redefinicao_senha;
